### ISSUE TITLE
4.3.8 PHP Warning (not in 4.3.7)

### ISSUE THREAD

**Issue by w3l** [PHPSocialNetwork/phpfastcache#243]
After upgrading phpfastcache to 4.3.8 from 4.3.7 i get a bunch of warnings in the log file:

[02-Mar-2016 23:31:28 Europe/Stockholm] PHP Warning:  file_exists(): open_basedir restriction in effect. File(/**secret**/Data/Library/phpFastCache/CacheManager.php) is not within the allowed path(s): (**secret**) in /**secret**/api/vendor/hoa/core/Consistency.php on line 354

[02-Mar-2016 23:31:28 Europe/Stockholm] PHP Warning:  file_exists(): open_basedir restriction in effect. File(/**secret**/Data/Library/phpFastCache/CacheManagerphpFastCache/CacheManager.php) is not within the allowed path(s): (**secret**) in /**secret**/api/vendor/hoa/core/Consistency.php on line 355

Not cure how hoa/core is related to phpFastCache but after downgrading phpfastcache to 4.3.7 the issue dispersal. Guessing it's an issue with your new autoloader? :)

**Comment by khoaofgod** [comment]
@Geolim4  : take a look at ur autoloader, bro

**Comment by khoaofgod** [comment]
@Geolim4 look open_basedir restriction effect on file_exists, so the simple way that I think is:
`ini_get('open_basedir')`

and compare with the path before do file_exists

**Comment by Geolim4** [comment]
I'll take a look this week, seems weird anyway :(

**Comment by Geolim4** [comment]
@w3l  After reviewing your error, it seem that's not an issue with our autoloader.
I did not introduced file_exists() in the autoloader but is_readable().

And the error is pretty clear:
File(/secret/Data/Library/phpFastCache/CacheManagerphpFastCache/CacheManager.php) is not within the allowed path(s): (secret) in /secret/api/vendor/hoa/core/Consistency.php on line 355

You called directly CacheManager.php from your file Consistency.php. Also there is a weird path:
/phpFastCache/**CacheManagerphpFastCache**/CacheManager.php

**Comment by khoaofgod** [comment]
@Geolim4  is_readable() still get warning by open_basedir
so if you check is_readable before file_exists, it still get the open_basedir warning.
hahahah

**Comment by khoaofgod** [comment]
@w3l can you verify about this path:
File(/secret/Data/Library/phpFastCache/CacheManagerphpFastCache/CacheManager.php) 
is it show on the error_log like that ?

**Comment by Geolim4** [comment]
Yeah but i don't get why the error is triggered outside the phpFastCache libs.

**Comment by khoaofgod** [comment]
oh yeah, shared hosting always got this problem, I will take a look tonight and you can optimize my update.

**Comment by Geolim4** [comment]
Yes, but i don't think that an additional check is necessary, it'll slow down the code and hide potential user code issue. Let's waiting more feedback of @w3l  :)

**Comment by w3l** [comment]
@Geolim4 I have not tuched "Consistency.php", hoa/core just seem to be required by some library. Because of the weird path i guessed the problem was because of your autoloader. This is how I use phpFastCache:

```php
require_once "/secret/api/vendor/autoload.php"; // Path to composer autoloader

use phpFastCache\CacheManager;
 
$cache = CacheManager::setup(array("storage" => "files", "path" => "cache", "htaccess" => true, "securityKey" => "auto"));
...
```
I never modify code in the composer-folder so the autoload.php and all required libraries are the way composer created them. :-)

Btw. the **secret** part of all paths posted is the same /path/to/domain/, just prefer not to publish that part publicly...

Just to make sure, I upgraded to 4.3.8 an additional time, got the warnings, downgrading to 4.3.7 again, no warnings.

IF its not a bug in your code then 4.3.8 adds conflicts with other libraries. None of these options are especially good.

**Comment by Geolim4** [comment]
Do you have a skype or something else to discuss privately ?

**Comment by w3l** [comment]
@Geolim4 Added Geolim4 on Skype, lets see if that was the correct Skype user... :-p

**Comment by Geolim4** [comment]
Yes it is, i'll be online tonight approximately. (8AM UTC+1)

**Comment by khoaofgod** [comment]
Fixed

**Comment by w3l** [comment]
Same issue with 4.3.10... :( Going back to 4.3.7 yet again...

**Comment by khoaofgod** [comment]
@w3l  what the .. heo.. LOL
1. Can you email the warning log to khoaofgod@gmail.com
2. can you run your phpinfo , copy the value of open_basedir and let me know too.
3. I need full path of this file: "Consistency.php"
4. And full path where you store phpFastCache

Thanks, I will debug the code and what different between 0.7 and 0.10

**Comment by w3l** [comment]
Sure, it's 11:35pm over here so I'll mail you the things requested tomorrow.

Very happy btw that you take bugs like this serious. :-)

**Comment by w3l** [comment]
Any chance of seeing a fix for this?

Didn't 4.3.8 contain "Implemented our own Autoload for non-composer users", as I said earlier, "Guessing it's an issue with your new autoloader? :)".

Why, btw, would you use your own autoloader with composer? Seems to complicate things. Why not just let composer handle the autoloading and provide your own autoloader as a stand-alone file for non-composer users? [PHPMailer](https://github.com/PHPMailer/PHPMailer) seems to have that approach for example...

**Comment by Geolim4** [comment]
After many tests we are sure that is not a part of our autoloader, in fact we never getting out of the open_base_dir.

We did not used composer autoload for the main reason that not everyone is using composer, some people use PhpFastCache vanilla, so it has been decided to implement our own composer.

Also i tried to catch you on skype but unfortunately you were often offline :(

**Comment by w3l** [comment]
@Geolim4 I gave it another try, I installed 4.3.11 yet again. Same issue.

I changed:
```php
require_once "/secret/api/vendor/autoload.php"; // Path to composer autoloader
```

to:
```php
require_once "/secret/api/vendor/phpfastcache/phpfastcache/src/autoload.php";
```

Guess what, no issues!

But I can't require 20+ packages individually because one of them don't play nicely with composer. Sure, I could use phpFastCache "vanilla" but my guess is that other composer-users has similar issues(even if it depends on environment, other packages, etc).

To sum things up:
* No issues with: 4.3.7
* I use 20+ other packages, no issues with any of them in my environment!
* 4.3.8-4.3.11 has some conflict with composer and/or other packages to generate warnings.
* Your autoloader works perfectly "vanilla", but in combination with composers generated autoloader something messes up somewhere.

> We did not used composer autoload for the main reason that not everyone is using composer, some people use PhpFastCache vanilla, so it has been decided to implement our own composer.

That is great! Provide an autoloader as a stand alone file, but let composer handle all the autoloading for composer users. Again, telling composers autoloader to use your autoloader just seems to complicate things...

**Comment by Geolim4** [comment]
Can you send me your composer.json to contact@geolim4.com please ?

Thanks you

**Comment by khoaofgod** [comment]
I believe something is wrong with composer.js , and if it happened it my fraud when I changed require phpfastcache/phpfastcache to phpFastCache/phpFastCache , it make the current dir become not existing anymore on Linux :D 
I changed back on 4.3.12 that I just fixed many bugs on March.

**Comment by Geolim4** [comment]
@khoaofgod I received the composer.json, i will have a look tonigh.

**Comment by khoaofgod** [comment]
I tested phpFastCache with composer and I don't see any problem.

This is how you can know the problem on your project:
First, 
Look at  Vendor/composer/autoload_files.php <-- copy this file content to your computer.

Then,
Update to phpFastCache latest version.
Go to Vendor/composer/autoload_files.php <-- compare this file with the one you backed up.

And see if the PATH of phpFastCache is changed or not. If it's not change, then verify the PATH on vendor/phpfastcache/phpfastcache/src/phpFastCache/phpFastCache.php <-- have to be like that. 

Case Sensitive. This word "phpFastCache" maybe wrong there, and make your project included wrong path. If it's wrong, just fix it on autoload_files.php and save.

Will be fix the problem and work for sure.

**Comment by Geolim4** [comment]
@khoaofgod I have the composer.json, i'll test it tomorrow :)

**Comment by w3l** [comment]
Sadly not fixed. :(

Based on http://stackoverflow.com/questions/31265030/can-individual-composer-dependencies-be-suppressed-from-autoloading it seems like hoa/* is autoloading some code that conflicts with phpFastCache. I guess this is an edge-case. I just have to move development dependencies to it's own folder. Ofc I would love to see a fix. But it just seem like older versions av hoa/* if just broken by design...

**Comment by khoaofgod** [comment]
so, basicly it's just conficts function with HOA. 
Then it will be easy, on morning, I will make a legacy that included everything of phpfastCache, then u just include that file = DONE.

**Comment by Geolim4** [comment]
I do need the driver that you use && your open_base_dir setting (in private if you want)

**Comment by Geolim4** [comment]
> That is great! Provide an autoloader as a stand alone file, but let composer handle all the autoloading for composer users. Again, telling composers autoloader to use your autoloader just seems to complicate things...

In fact if you look at the ReCaptcha lib: https://github.com/google/recaptcha/blob/master/src/autoload.php

We do exactly the same thing :(

**Comment by Geolim4** [comment]
Can you open: vendor/composer/installed.json

And replace phpFastCache autoload with this one:


        "autoload": {
            "psr-0": {
                "": "src/"
            },
            "files": [
                "src/phpFastCache/phpFastCache.php"
            ]
        }`
And then make a composer update.
(Check after the composer update that the psr-0 key is always present).
If it work then i potentially identified a bug with hoa library :)

**Comment by khoaofgod** [comment]
@w3l 
This will fix ur problem for sure.
https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/4.3.14

On your index.php or config.php / whatever file store configuration which is loaded first before composer load. Copy & paste this line on it ( on examples folder have it now ).

`define("PHPFASTCACHE_LEGACY",true);`

Then the rest will let Composer handle autoload, it will skip our autoload. You can just keep that line anytime you upgrade phpFastCache. It stay no problem.

**Comment by w3l** [comment]
@khoaofgod Yes! That fixed my issue for sure!

```php
define("PHPFASTCACHE_LEGACY", true);
```

Worked perfectly!

This issue would disappear when https://github.com/phpmetrics/PhpMetrics drops php 5.4 support and start using hoa/ruler 2.* instead of hoa/ruler 1.*. (The conflict with phpFastCache seems to be in hoa/ruler 1.*). But I am very happy you guys could fix the issue! Thanks a lot!
